from .drone import Drone
from .obstacles import Obstacles
from .config import SCREEN_WIDTH, SCREEN_HEIGHT, DRONE_SIZE, COLOURS, SENSOR_COUNT
from .config import SENSOR_FOV, SENSOR_LENGHT, OBSTACLE_COUNT, OBSTACLE_MIN_SIZE, OBSTACLE_MAX_SIZE, TURN_RATE_DEG_PER_SEC, TURN_TOLERANCE, INFLUENCE_FACTOR, BASE_SPEED